---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlmodel-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: mlmodel
  template:
    metadata:
      labels:
        app: mlmodel
    spec:
      containers:
        - name: mlmodel-container
          image: fredyball/mlmodel:0.0.1
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: mlmodel-service
spec:
  selector:
    app: mlmodel
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer